name: Build AuthPatch

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 8

    - name: Build with Maven
      run: mvn -B package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          target/*.jar
          target/*.txt

  publish:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifact/AuthPatch.jar
